name: CI
on:
  pull_request:
    branches:
      - main

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: windows
    steps:
      - uses: actions/checkout@vs
      - uses: actions/setup-java@v2
        with:
          java-version: "12.x"
      - uses: subosito/flutter-actions@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
